import { Activity, ArrowUpRight, Footprints, RotateCcw, Scale, Trash2, TrendingUp } from 'lucide-react'
import { useState } from 'react'
import type { AppData } from '../domain/models'
import { deleteWeightEntry, getWeightEntries } from '../services/appService'

export function ProgressScreen({ data, onData }: { data: AppData; onData: (edit: (data: AppData) => AppData) => void }) {
  const completed = data.sessions.filter(session => session.completedAt)
  const workingSets = completed.reduce((sum, session) => sum + session.exercises.reduce((count, log) => count + log.sets.filter(set => set.completed).length, 0), 0)
  const weights = getWeightEntries(data)
  const [deleteId, setDeleteId] = useState<string | null>(null)
  const areas = [
    { title: 'Weight', icon: Scale, description: weights.length ? `${weights[0].weightKg.toFixed(1)} kg latest · ${weights.length} weigh-in${weights.length === 1 ? '' : 's'}` : 'Add a few weigh-ins to begin seeing your trend.', value: weights.length ? `${weights[0].weightKg.toFixed(1)} kg` : '—' },
    { title: 'Training sessions', icon: Activity, description: 'Completed and saved workouts.', value: String(completed.length) },
    { title: 'Returns', icon: RotateCcw, description: 'RESET sessions saved as return evidence.', value: String(data.returnEvents.length) },
    { title: 'Running stage', icon: Footprints, description: 'Progress comes from capacity, not elapsed weeks.', value: data.profile.runningStage },
    { title: 'Strength progress', icon: TrendingUp, description: 'Working sets recorded across saved sessions.', value: workingSets ? String(workingSets) : '—' },
  ]
  const starting = weights.at(-1)?.weightKg
  const change = starting !== undefined && weights[0] ? weights[0].weightKg - starting : undefined
  return <div className="screen-content"><div className="page-intro"><div><p className="eyebrow blue">EVIDENCE OVER PERFECTION</p><h1>Progress</h1><p className="muted">A long view of the work you actually do.</p></div></div><div className="progress-statement"><span className="eyebrow">CURRENT STAGE</span><div><strong>{data.profile.runningStage}</strong><ArrowUpRight size={23}/></div><p>Building the foundation for running.</p></div><section className="section-block"><div className="section-title"><div><span className="eyebrow">YOUR EVIDENCE</span><h3>Progress areas</h3></div></div><div className="progress-list">{areas.map(({ title, icon: Icon, description, value }) => <div className="progress-item" key={title}><div className="progress-icon"><Icon size={19}/></div><div><h4>{title}</h4><p>{description}</p></div><span>{value}</span></div>)}</div></section><section className="section-block weight-history"><div className="section-title"><div><span className="eyebrow">WEIGHT</span><h3>Weight history</h3></div><span className="soft-label">LATEST {weights[0]?.weightKg.toFixed(1) ?? '—'} KG</span></div>{weights.length >= 2 ? <div className="weight-chart" aria-label="Weight trend chart"><svg viewBox="0 0 360 120" role="img"><polyline points={weights.slice().reverse().map((entry, index, list) => `${index * (350 / Math.max(1, list.length - 1)) + 5},${110 - ((entry.weightKg - Math.min(...weights.map(item => item.weightKg))) / Math.max(1, Math.max(...weights.map(item => item.weightKg)) - Math.min(...weights.map(item => item.weightKg)))) * 85}`).join(' ')} /></svg><p>Individual weigh-ins move around. The trend matters.</p></div> : <div className="empty-state">Add a few weigh-ins to begin seeing your trend.</div>}<div className="weight-summary"><span>Starting <strong>{starting?.toFixed(1) ?? data.profile.baselineWeightKg.toFixed(1)} kg</strong></span><span>Change <strong>{change === undefined ? '—' : `${change > 0 ? '+' : ''}${change.toFixed(1)} kg`}</strong></span></div>{weights.map(entry => <div className="weight-row" key={entry.id}><div><strong>{new Intl.DateTimeFormat('en-US', { day: 'numeric', month: 'short', year: 'numeric' }).format(new Date(`${entry.date}T12:00:00`))}</strong><small>{entry.note ?? 'Weigh-in'}</small></div><b>{entry.weightKg.toFixed(1)} kg</b><button className="icon-button" aria-label={`Delete weight entry ${entry.date}`} onClick={() => setDeleteId(entry.id)}><Trash2 size={16}/></button></div>)}</section>{deleteId && <div className="dialog-backdrop"><div className="confirm-dialog" role="dialog" aria-modal="true" aria-labelledby="delete-weight-title"><h2 id="delete-weight-title">DELETE WEIGHT ENTRY?</h2><p>Remove this weigh-in?</p><div className="dialog-actions"><button type="button" onClick={() => setDeleteId(null)}>CANCEL</button><button type="button" className="dialog-delete" onClick={() => { onData(current => deleteWeightEntry(current, deleteId)); setDeleteId(null) }}>DELETE</button></div></div></div>}</div>
}
